default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: merlin_notifier_development

test:
  <<: *default
  database: merlin_notifier_test

production:
  <<: *default
  database: merlin_notifier_production
  username: merlin_notifier
  password: <%= ENV["MERLIN_NOTIFIER_DATABASE_PASSWORD"] %>
