default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: merlin_notifier_development
  portal:
    <<: *default
    database: portal_development

test:
  primary:
    <<: *default
    database: merlin_notifier_test
  portal:
    <<: *default
    database: portal_test

production:
  primary:
    <<: *default
    database: merlin_notifier_production
    username: merlin_notifier
    password: <%= ENV["MERLIN_NOTIFIER_DATABASE_PASSWORD"] %>
  portal:
    <<: *default
    database: portal_production
    username: portal
    password: <%= ENV["PORTAL_DATABASE_PASSWORD"] %>
